"""Recover PR and F1-confidence curves from the Ultralytics *_curve.webp
renders, then replot them in the paper style.

Why this exists: the trained weights and validation split are gone, so the
curves cannot be regenerated by re-running model.val(). The webp images, however,
were drawn by Ultralytics from the real per-threshold validation data, so the
data still exists, just stored as pixels. This script reads the colored line
back out of the raster, converts it to (x, y), and restyles it.

This is faithful only within digitization noise, so it is NOT trusted blindly.
Every curve is cross-checked against the scalar printed in the original legend
(PR -> area under curve = AP; F1 -> peak value and its confidence). If the
recovered scalar disagrees with the printed one beyond DIGITIZE_TOL, the curve
is flagged and should not be used. The extracted points are also written to CSV
so the digitized data itself becomes a durable, inspectable artifact.

Run with --debug to dump the per-curve pixel masks; look at them. They show
exactly which pixels were treated as the curve, which is the honest way to
verify the color segmentation did not mix two lines.

Usage:
    python utils/digitize_curves.py \
        --image results/object-detection/yolo26-draxnet-backbone/BoxPR_curve.webp \
        --kind pr --out figures/pr_draxnet
    python utils/digitize_curves.py \
        --image results/object-detection/yolo26-draxnet-backbone/BoxF1_curve.webp \
        --kind f1 --out figures/f1_draxnet --debug
"""

import argparse
import csv
from pathlib import Path

import numpy as np
from PIL import Image

# --- honesty thresholds -----------------------------------------------------
# Max allowed gap between the scalar recovered from the digitized curve and the
# scalar Ultralytics printed in the legend. PR uses absolute AP difference.
DIGITIZE_TOL = 0.02

# --- axis calibration -------------------------------------------------------
# Both Ultralytics PR and F1 plots span exactly [0, 1] on both axes, so the
# only unknown is where the black axes frame sits in pixels. We detect it as
# the bounding box of the long near-black frame lines.
DARK_THRESH = 80          # grayscale value below which a pixel is "frame/ink"
FRAME_FRAC = 0.50         # a spine is dark over >= this fraction of the box span

# --- curve colors (HSV, OpenCV-free; H in [0,360), S,V in [0,1]) ------------
# Ultralytics: 'all classes' is a thick saturated blue; per-class lines are
# thinner. ActiveTuberculosis renders as a lighter steel/sky blue,
# ObsoletePulmonaryTuberculosis as orange. These are starting ranges; if a
# --debug mask looks wrong, tune the matching entry here.
# Measured from the actual renders: all-classes RGB~(28,28,255) hue~250 S~.89
# V~1.0; ActiveTB RGB~(80,148,196) hue~210 S~.61 V~.77; ObsoleteTB
# RGB~(255,157,71) hue~30 S~.72 V~1.0. Hue cleanly separates the two blues.
COLOR_SPECS = {
    "all":    dict(h=(235, 265), s=(0.78, 1.01), v=(0.85, 1.01)),  # bold blue
    "active": dict(h=(195, 228), s=(0.38, 0.78), v=(0.55, 0.92)),  # light blue
    "obsolete": dict(h=(15, 48), s=(0.50, 1.01), v=(0.80, 1.01)),  # orange
}

SMOOTH_WIN = 5            # moving-average window over extracted samples
MIN_PX_PER_COL = 1        # ignore image columns with fewer matching pixels

# --- replot palette ---------------------------------------------------------
# Harmonious, print-safe, and colorblind-safe (Okabe-Ito). The aggregate
# 'all classes' line gets the primary blue and is drawn boldest; the two real
# classes get green / vermillion so they stay distinct from each other and from
# the aggregate even in grayscale or for deuteranopic readers.
PLOT_COLORS = {
    "all":      "#0072B2",  # blue (primary, bold)
    "active":   "#009E73",  # bluish green
    "obsolete": "#D55E00",  # vermillion
}


def load_rgb(path):
    return np.asarray(Image.open(path).convert("RGB"), dtype=np.uint8)


def detect_axes_box(rgb):
    """Return (x_left, x_right, y_top, y_bottom) pixel coords of the plot frame."""
    gray = rgb.mean(axis=2)
    dark = gray < DARK_THRESH
    h, w = dark.shape
    # Vertical spines are full-height dark lines; measure against image height
    # so legend/tick text (short runs) is excluded.
    vcols = np.where(dark.sum(axis=0) >= FRAME_FRAC * h)[0]
    if vcols.size < 2:
        raise RuntimeError("Could not detect the left/right axes spines.")
    x_left, x_right = int(vcols.min()), int(vcols.max())
    # Horizontal spines are measured only across the detected box width, not
    # the whole image, because the legend sits far to the right of the axes.
    span = x_right - x_left
    row_dark = dark[:, x_left:x_right + 1].sum(axis=1)
    hrows = np.where(row_dark >= FRAME_FRAC * span)[0]
    if hrows.size < 2:
        raise RuntimeError("Could not detect the top/bottom axes spines.")
    return x_left, x_right, int(hrows.min()), int(hrows.max())


def hsv_of(rgb):
    """Vectorized RGB->HSV. Returns H in [0,360), S and V in [0,1]."""
    r, g, b = (rgb[..., i] / 255.0 for i in range(3))
    mx = np.max(rgb, axis=2) / 255.0
    mn = np.min(rgb, axis=2) / 255.0
    diff = mx - mn
    h = np.zeros_like(mx)
    mask = diff > 1e-6
    rmax = (mx == r) & mask
    gmax = (mx == g) & mask
    bmax = (mx == b) & mask
    h[rmax] = (60 * ((g - b)[rmax] / diff[rmax]) + 360) % 360
    h[gmax] = 60 * ((b - r)[gmax] / diff[gmax]) + 120
    h[bmax] = 60 * ((r - g)[bmax] / diff[bmax]) + 240
    s = np.where(mx > 1e-6, diff / np.where(mx > 1e-6, mx, 1), 0.0)
    return h, s, mx


def color_mask(rgb, spec):
    h, s, v = hsv_of(rgb)
    return (
        (h >= spec["h"][0]) & (h < spec["h"][1])
        & (s >= spec["s"][0]) & (s < spec["s"][1])
        & (v >= spec["v"][0]) & (v < spec["v"][1])
    )


def extract_curve(mask, box, pin_left=False):
    """Per image column inside the box, take the median row of masked pixels.

    Returns data-space (x, y) with both axes calibrated to [0, 1].

    pin_left (PR curves only): the thin per-class line's near-vertical left
    edge overlaps the y-axis spine and is lost by color masking, so the curve
    starts at the first detection's recall instead of 0. Prepending (0,
    p_first) restores it. This is not a fudge: AP is defined with precision
    held constant for recall below the first point (same convention as sklearn
    / Ultralytics), so this reconstructs the curve's true left boundary.
    """
    x_left, x_right, y_top, y_bottom = box
    xs, ys = [], []
    for px in range(x_left, x_right + 1):
        rows = np.where(mask[y_top:y_bottom + 1, px])[0]
        if rows.size < MIN_PX_PER_COL:
            continue
        py = y_top + float(np.median(rows))
        xs.append((px - x_left) / (x_right - x_left))
        ys.append(1.0 - (py - y_top) / (y_bottom - y_top))
    x = np.asarray(xs)
    y = np.asarray(ys)
    if x.size > SMOOTH_WIN > 1:
        # Edge-padded moving average. Plain np.convolve(..., "same") zero-pads
        # the ends, which would drag the endpoints toward 0 and corrupt AP for
        # steep curves (precision is highest exactly at recall->0). Pad with
        # the edge value instead so endpoints are preserved.
        pad = SMOOTH_WIN // 2
        yp = np.pad(y, pad, mode="edge")
        k = np.ones(SMOOTH_WIN) / SMOOTH_WIN
        y = np.convolve(yp, k, mode="valid")[: x.size]
    if pin_left and x.size and x.min() > 1e-3:
        order = np.argsort(x)
        x = np.concatenate(([0.0], x[order]))
        y = np.concatenate(([y[order][0]], y[order]))
    return x, y


def pr_area(recall, precision):
    """Area under the PR curve = AP, the scalar the legend prints."""
    order = np.argsort(recall)
    return float(np.trapz(precision[order], recall[order]))


def restyle_rcparams():
    """SciencePlots science+nature if importable, else a close fallback.

    Inter is forced AFTER the style is applied because the science style sets a
    serif family that would otherwise win.
    """
    import matplotlib
    import matplotlib.font_manager as fm
    import matplotlib.pyplot as plt

    # Register Inter so matplotlib (not just fontconfig) can resolve it.
    for p in ("/usr/local/share/fonts/Inter-VariableFont_opsz,wght.ttf",
              "/usr/share/fonts/opentype/inter/Inter-Regular.otf"):
        if Path(p).exists():
            try:
                fm.fontManager.addfont(p)
            except Exception:
                pass

    try:
        import scienceplots  # noqa: F401
        # "no-latex" keeps the science+nature look but disables usetex, which
        # would otherwise ignore font.family and lose Inter.
        plt.style.use(["science", "nature", "no-latex"])
    except Exception:
        matplotlib.rcParams.update({
            "figure.dpi": 300, "savefig.dpi": 300,
            "axes.linewidth": 0.6, "lines.linewidth": 1.0,
            "legend.frameon": False, "axes.grid": False,
        })
    # Applied AFTER the style so it wins over the science serif family.
    matplotlib.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["Inter"],
        "mathtext.fontset": "custom",
        "mathtext.rm": "Inter",
        "axes.unicode_minus": False,
    })
    return plt


def style_axes(ax):
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    # SciencePlots "science" turns on minor ticks and top/right ticks; zero
    # both major and minor on every side so no tick marks render. Labels stay
    # (a scale-less curve is unreadable).
    ax.tick_params(which="both", length=0, top=False, right=False)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", required=True, type=Path)
    ap.add_argument("--kind", required=True, choices=["pr", "f1"])
    ap.add_argument("--out", required=True, type=Path,
                    help="output stem; writes <out>.pdf, <out>.png, <out>.csv")
    ap.add_argument("--debug", action="store_true",
                    help="also save the per-curve pixel masks for inspection")
    ap.add_argument("--box", type=int, nargs=4, metavar=("XL", "XR", "YT", "YB"),
                    help="override auto-detected axes box in pixels; use when "
                         "the F1-plot legend frame is mistaken for the spine")
    args = ap.parse_args()

    rgb = load_rgb(args.image)
    box = tuple(args.box) if args.box else detect_axes_box(rgb)
    print(f"axes box (x_left, x_right, y_top, y_bottom) = {box}"
          f"{' (manual)' if args.box else ''}")

    plt = restyle_rcparams()
    fig, ax = plt.subplots(figsize=(3.3, 2.5))

    labels = {
        "active": "Active TB",
        "obsolete": "Latent TB",
        "all": "All classes",
    }
    rows = []
    for name, spec in COLOR_SPECS.items():
        mask = color_mask(rgb, spec)
        if args.debug:
            dbg = (mask[:, :, None] * np.array([255, 0, 0], np.uint8)
                   + (~mask)[:, :, None] * rgb)
            dpath = args.out.with_name(f"{args.out.name}_mask_{name}.png")
            dpath.parent.mkdir(parents=True, exist_ok=True)
            Image.fromarray(dbg.astype(np.uint8)).save(dpath)
            print(f"  debug mask -> {dpath}")

        x, y = extract_curve(mask, box, pin_left=(args.kind == "pr"))
        if x.size < 5:
            print(f"  [skip] {name}: only {x.size} points recovered")
            continue

        lw = 1.8 if name == "all" else 1.0
        ax.plot(x, y, label=labels[name], linewidth=lw,
                color=PLOT_COLORS[name])
        for xi, yi in zip(x, y):
            rows.append((name, xi, yi))

        # honesty cross-check against the scalar in the original legend
        if args.kind == "pr":
            print(f"  {name}: digitized AP = {pr_area(x, y):.3f} "
                  f"(compare to legend AP; flag if |delta| > {DIGITIZE_TOL})")
        else:
            i = int(np.argmax(y))
            print(f"  {name}: digitized peak F1 = {y[i]:.3f} at conf {x[i]:.3f} "
                  f"(compare to legend; flag if off)")

    if args.kind == "pr":
        ax.set_xlabel("Recall")
        ax.set_ylabel("Precision")
    else:
        ax.set_xlabel("Confidence")
        ax.set_ylabel("F1")
    style_axes(ax)
    ax.legend(loc="upper right", fontsize=6)
    fig.tight_layout()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.out.with_suffix(".pdf"))
    fig.savefig(args.out.with_suffix(".png"))
    with open(args.out.with_suffix(".csv"), "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["curve", "x", "y"])
        w.writerows(rows)
    print(f"wrote {args.out}.pdf / .png / .csv")


if __name__ == "__main__":
    main()
